# Generated by Django 3.2.9 on 2021-12-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='production_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.productionsite', verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(to='staff.Specialization', verbose_name='Specjalizacja'),
        ),
    ]
