# Generated by Django 3.2.9 on 2021-11-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('150x105', '150cm x 105cm'), ('250x175', '250cm x 175cm'), ('350x256', '350cm x 256cm'), ('450x315', '450cm x 315cm'), ('50x1050', '50cm x 1050cm')], max_length=7)),
                ('type', models.CharField(choices=[('T', 'Tapeta'), ('F', 'Fototapeta')], max_length=1)),
                ('pattern_index', models.IntegerField()),
                ('production_step', models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie druku', 'W trakcie druku'), ('wydrukowane', 'Wydrukowane'), ('w trakcie pakowania', 'W trakcie pakowania'), ('zapakowane', 'Zapakowane')], default=('nowe', 'Nowe'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateField()),
                ('complete_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie realizacji', 'W trakcie realizacji'), ('zrealizowane', 'Zrealizowane'), ('wydane do wysyłki', 'Wydane do wysyłki')], default=('nowe', 'Nowe'), max_length=20)),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packer', to='staff.employee')),
                ('printer_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_operator', to='staff.employee')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.productionsite')),
                ('products', models.ManyToManyField(to='orders.Product')),
                ('shipping_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
    ]
