# Generated by Django 3.2.9 on 2021-12-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20211207_1821'),
        ('orders', '0003_auto_20211126_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_order_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data realizacji'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name='Data złożenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packer', to='staff.employee', verbose_name='Osoba pakująca'),
        ),
        migrations.AlterField(
            model_name='order',
            name='printer_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_operator', to='staff.employee', verbose_name='Osoba drukująca'),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.productionsite', verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Dane do wysyłki'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie realizacji', 'W trakcie realizacji'), ('zrealizowane', 'Zrealizowane'), ('wydane do wysyłki', 'Wydane do wysyłki')], default='nowe', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pattern_index',
            field=models.IntegerField(verbose_name='Numer wzoru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_step',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie druku', 'W trakcie druku'), ('wydrukowane', 'Wydrukowane'), ('w trakcie pakowania', 'W trakcie pakowania'), ('zapakowane', 'Zapakowane')], default='nowe', max_length=20, verbose_name='Etap produkcji'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('150x105', '150cm x 105cm'), ('250x175', '250cm x 175cm'), ('350x256', '350cm x 256cm'), ('450x315', '450cm x 315cm'), ('50x1050', '50cm x 1050cm')], max_length=7, verbose_name='Rozmiar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('T', 'Tapeta'), ('F', 'Fototapeta')], max_length=1, verbose_name='Typ'),
        ),
    ]
